### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element ...

### ISSUE THREAD

**Issue by tim6her** [rgawenda/atom-move-status-items#9] opened 2019-04-21 14:31 UTC
[Enter steps to reproduce:]

1. Open Atom.io in macOS

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [move-status-items](https://github.com/olmokramer/atom-move-status-items) package 0.0.11

### Stack Trace

Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```
At /Users/timbenediktherbstrith/.atom/packages/move-status-items/lib/move-status-items.js:131

Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at setInitialOrder (/packages/move-status-items/lib/move-status-items.js:131:27)
    at /packages/move-status-items/lib/move-status-items.js:16:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-dark-fusion-syntax 2.2.1 
atom-html-preview 0.2.6 
atom-play-piano 3.2.1 
auto-indent 0.5.0 
autocomplete-bibtex 1.2.1 
autocomplete-haskell 1.0.1 
autocomplete-python 1.14.0 
build 0.70.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 2.0.1 
cake-syntax 1.0.2 
color-picker 2.3.0 
dictionary 0.5.0 
editorconfig 2.4.0 
expose 0.15.0 
file-icons 2.1.31 
git-plus 8.6.2 
git-time-machine 2.1.0 
hard-wrap 1.7.1 
haskell-ghc-mod 2.2.5 
haskell-grammar 0.4.0 
hex-view 0.2.1 
highlight-selected 0.16.0 
ide-haskell 2.4.0 
ide-haskell-cabal 2.2.1 
ide-haskell-repl 0.8.7 
intentions 1.1.5 
language-haskell 1.18.0 
language-latex 1.2.0 
language-markdown 0.29.0 
language-restructuredtext 1.1.2 
language-sphinx 0.1.9 
language-weave 0.6.2 
latex 0.50.2 
latexer 0.3.0 
linter 2.3.0 
linter-chktex 1.4.0 
linter-hlint 2.1.0 
linter-markdown 5.2.6 
linter-pylint 2.1.1 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.7.1 
markdown-folding 0.3.1 
markdown-preview-plus 3.8.1 
markdown-table-editor 1.1.1 
markdown-themeable-pdf 1.2.1 
markdown-toc 0.4.2 
markdown-writer 2.11.5 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-titles 1.15.0 
move-status-items 0.0.11 
native-ui 0.27.0 
one-o-eight-syntax 0.38.0 
outlander-syntax 2.0.0 
pdf-view 0.71.0 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
rst-preview 1.3.1 
script 3.18.1 
sort-lines 0.19.0 
split-diff 1.6.0 
todo-show 2.3.2 
```

**Comment by tim6her** [comment] 2019-04-21 14:31
I am happy to contribute if you point me in the right direction.

**Comment by sbrl** [comment] 2019-11-30 17:41
Duplicate of #5, I think.

**Closed** 2019-12-02 11:40 UTC
