### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element ...

### ISSUE THREAD

**Issue by LeptoSpira** [rgawenda/atom-move-status-items#11] opened 2019-05-27 05:01 UTC
[Enter steps to reproduce:]

1. Install packages
2. Move the busy-signal the left instead of the right
3. Move the project to the left instead of the right
4. Reload the window

**Atom**: 1.38.0-beta0 x64
**Electron**: 2.0.18
**OS**: Ubuntu 19.04
**Thrown From**: [move-status-items](https://github.com/olmokramer/atom-move-status-items) package 0.0.11

### Stack Trace

Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```
At /home/leptospira/.atom/packages/move-status-items/lib/move-status-items.js:131

Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at setInitialOrder (/packages/move-status-items/lib/move-status-items.js:131:27)
    at /packages/move-status-items/lib/move-status-items.js:16:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
Window: Reload
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
color-picker 2.3.0 
ex-mode 0.18.0 
Hydrogen 2.9.0 
ide-rust 0.20.2 
kite 0.162.0 
lang-gdscript 4.1.1 
language-batch 0.4.0 
language-tibasic 0.2.0 
linter-pylint 2.1.1 
minimap 4.29.9 
mouse-autohide 1.0.0 
move-status-items 0.0.11 
multi-wrap-guide 1.1.6 
neutron-dark-ui 2.1.4 
pdf-view 0.71.0 
project-viewer 1.3.1 
python-black 0.7.0 
relative-numbers 0.9.0 
resize-panes 0.2.0 
sequential-number 0.5.0 
seti-icons 1.5.4 
seti-syntax 1.2.0 
sync-settings 0.8.6 
teletype 0.13.4 
vim-mode-plus 1.36.0 
```

**Comment by sbrl** [comment] 2019-11-30 17:42
Duplicate of #5, I think.

**Closed** 2019-12-02 11:40 UTC
