### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element ...

### ISSUE THREAD

**Issue by spacesamurai** [rgawenda/atom-move-status-items#12] opened 2019-07-12 19:56 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.10
**Thrown From**: [move-status-items](https://github.com/olmokramer/atom-move-status-items) package 0.0.11

### Stack Trace

Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```
At /home/spacesamurai/.atom/packages/move-status-items/lib/move-status-items.js:131

Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at setInitialOrder (/packages/move-status-items/lib/move-status-items.js:131:27)
    at /packages/move-status-items/lib/move-status-items.js:16:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
atom-material-contrast-syntax 0.3.1 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-python-run 0.9.7 
atom-python-virtualenv 1.0.3 
autoclose-html 0.23.0 
autocomplete-python 1.14.1 
base16-ocean-dark-syntax-theme 0.1.10 
build 0.70.0 
build-python 0.11.0 
busy-signal 2.0.1 
chameleon-dark-syntax 0.0.5 
color-picker 2.3.0 
colorblind-wombat-dark-syntax 0.6.0 
drag-drop-text 0.1.4 
editor-stats 0.17.0 
git-plus 8.7.1 
highlight-line 0.12.0 
highlight-selected 0.16.0 
hover-tooltips 0.3.0 
ide-php 0.7.18 
ide-python 1.4.1 
increment-selection 0.3.0 
intentions 1.1.5 
isotope-ui 2.8.5 
linter 2.3.0 
linter-php 1.6.1 
linter-ui-default 1.7.1 
material-ui 1.0.10 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
move-status-items 0.0.11 
multi-highlight-selected 2.0.0 
neon-syntax 0.3.7 
nord-atom-ui 0.11.0 
northem-dark-atom-syntax 2.1.0 
one-o-eight-syntax 0.38.0 
open-recent 5.0.0 
php-cs-fixer 4.1.1 
php-debug 0.3.5 
php-hyperclick 1.2.1 
php-ide-serenata 4.5.3 
php-integrator-autocomplete-plus 1.6.2 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
project-manager 3.3.7 
python-debugger 0.2.0 
python-indent 1.2.3 
python-tools 0.6.9 
remote-ftp 2.2.2 
run-python-simply 0.6.0 
script 3.18.1 
selection-highlight 0.1.6 
set-syntax 0.4.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
simple-drag-drop-text 0.4.0 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 0.8.6 
tab-numbers 0.6.1 
terminal-plus 0.14.5 
ubik-hackerman-syntax 1.10.0 
wombat-dark-syntax 1.2.0 
```

**Comment by sbrl** [comment] 2019-11-30 17:42
Duplicate of #5, I think.

**Closed** 2019-12-02 11:40 UTC
